import("//kernel/liteos_m/liteos.gni")
module_name = "gd32f470zi"
kernel_module(module_name) {
    sources = [
        "startup.S",

        # libc
        "libc/dprintf.c",
        "libc/dstring.c",
        
        # driver
        "driver/system_gd32f4xx.c",
        "driver/systick.c",
 
        #RTT
        "third_party/RTT/SEGGER_RTT_printf.c",
        "third_party/RTT/SEGGER_RTT.c",

        #SRC
        "main.c",
        "main_task.c",
    ]
    deps = [
        "//device/soc/gd/gd32f4xx/sdk:gd32f4xx_sdk",
    ]
    visibility += [ "${root_build_dir}/*" ]
}

