import("//kernel/liteos_m/liteos.gni")
module_name = "gd32f470"
kernel_module(module_name) {
    sources = [
        "startup.S",
 
        # driver
        "driver/system_gd32f4xx.c",
        "driver/systick.c",
        "driver/uart_drv.c",
        "driver/wdg_drv.c",
        "driver/rtc_drv.c",
        "driver/dwt_drv.c",
        
        #norflash
        "driver/norflash/bsp_w25qxx.c",
        "driver/norflash/data_test.c",
        "driver/norflash/w25qxx.c",

        # shell
        "third_party/shell/shell_cmd_list.c",
        "third_party/shell/shell.c",
        "third_party/shell/shell_port.c",
        "third_party/shell/shell_companion.c",
        "third_party/shell/shell_ext.c",

        #RTT
        "third_party/RTT/SEGGER_RTT_printf.c",
        "third_party/RTT/SEGGER_RTT.c",

        "libc/dprintf.c",
        "libc/dstring.c",
        "common/common_time.c",
        "kernel/los_shell_cmd.c",
        "main.c",
        "utils.c",
        "periph_gpio.c",
        "periph_uart.c",
        "main_task.c",
        "di_task.c",
        "adc_task.c",
        "periph_spi_flash.c",
        "periph_spi_adc.c",
        "periph_ethernet.c",
        "message_queue.c",
        "modbus_rtu_task.c",
        "modbus_rtu.c",
    ]
    deps = [
        "//device/soc/gd/gd32f4xx/sdk:gd32f4xx_sdk",
    ]
    visibility += [ "${root_build_dir}/*" ]
}

